server:
  session-timeout: 1800
  port: 8899
  servlet:
    context-path: /teacher-platform-face
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: teacher-platform-face
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jmx:
    enabled: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  devtools:
    restart:
      enabled: true
  cache:
#    type: ehcache
    type: redis
    ehcache:
      config: classpath:config/ehcache.xml
#  日志输出颜色变化开启
  output:
    ansi:
      enabled: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
#  typeAliasesPackage: com.hx.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
# ModularRealmAuthorizer
#版本管理 -- 文件上传保存的路径
#breakpoint:
#  upload:
    #1024*1024=1 048 576,5M=5 242 880
#    chunkSize: 5 242 880

#ribbon:
  #配置单个节点重试最大值,不含首次,总请求次数(与提供的服务数量无关)= (1+MaxAutoRetriesNextServer) * (1 + maxAutoRetries)
  #全部超时的情况下(未考虑连接超时的情况) 响应时间 = 总请求次数 * ReadTimeout
#  MaxAutoRetries: 0
  #配置更换节点数最大值,不含首次
#  MaxAutoRetriesNextServer: 0
  #链接超时时间
#  ConnectTimeout: 5000
  #请求处理时间
#  ReadTimeout: 5000
  #每个操作都开启重试机制
#  OkToRetryOnAllOperations: false
